<div class="about">
	<a href="http://klasemate.arcestia.id" target="_blank"><img src="themes/default-light/images/logo.png" height="50" alt="Klasemate"></a>
	<p class="small"><strong><?php __($community_name) ?></strong> is proudly powered by:</p>
	<div class="box">
		<span class="small">Klasemate <?php __($data['version']) ?></span><br><br>
		&copy; 2016 - Klasemate and its licensors. All rights reserved.<br>
		Documentation and source at <a href="http://klasemate.arcestia.id" target="_blank">GitHub</a>. Found a bug? Report it <a href="http://klasemate.arcestia.id/issues" target="_blank">here</a>!
	</div>
</div>
