<div class="title-bar">
	<div class="title fleft"><span><?php __($community_name) ?></span><?php __( (substr( $message['subject'], 0, 3 ) === "Re:") ? $message['subject'] : "Re:". $message['subject'] ) ?>;@<?php __($message['username']) ?>;</div>
	<?php if(Http::Request("is") != "sent"): ?>
	<?php endif; ?>
</div>

<div class="box">
	<form action="messenger/sendReply" method="post" class="validate">

		<input type="hidden" name="to" value="<?php __($message['from_id']) ?>">
    <input type="hidden" name="subject" value="<?php __($message['subject']) ?>">
		<div class="input-box">
			<div class="label"><?php __("M_MESSAGE") ?></div>
			<div class="field">
				<textarea name="post" id="post" class="full" rows="12"></textarea>
			</div>
		</div>
		<div class="fleft">
			<div class="error-message"><?php __("M_PM_ERROR") ?></div>
		</div>
		<div class="fright">
			<input type="submit" value="<?php __("M_SEND") ?>">
		</div>
	</form>
</div>
